name: pypi-publish
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    if: ${{ true }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }},
      - name: Install dependencies
        run: |
          pip install -e .
      - name: Build package
        run: |
          pip install --upgrade build
          python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
